name: SST workflow
on: 
  pull_request:
    types: [opened, synchronize]

# Concurrency group name ensures concurrent workflow runs wait for any in-progress job to finish
concurrency:
  group: merge-${{ github.ref }}

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  lint-typescript:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.0

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Download deps
        run: npm install

      - name: Lint
        run: npm run lint:js

  typecheck:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.0

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Download deps
        run: npm install

      - name: Build app
        run: npm run build

      - name: Type check
        run: npm run typecheck

  DeployAppDev:
    name: Deploy to dev
    needs: [ lint-typescript, typecheck ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ROLE }}
          role-duration-seconds: 14390 #adjust as needed for your build time
          aws-region: eu-west-2

      - name: Deploy app
        run: |
          npm i && npx sst deploy --stage dev
